### ISSUE TITLE
Error finding  QPOASES files

### ISSUE THREAD

**Issue by michaelchi08** [icsl-Jeon/traj_gen#1]
/catkin_ws/src/traj_gen/include/traj_gen/qpOASES.hpp:66:33: fatal error: qpOASES/QProblemB.hpp: No such file or directory
 #include <qpOASES/QProblemB.hpp>
                                 ^
compilation terminated.
traj_gen/CMakeFiles/traj_gen_client.dir/build.make:72: recipe for target 'traj_gen/CMakeFiles/traj_gen_client.dir/qt_ui/main.cpp.o' failed

Hello,

I did follow the steps in the instructions but for some reason, cmake isn't able to find the qpoases files it needs. Do you know what might be going on?

Thanks

**Comment by michaelchi08** [comment]
n file included from /home/michael/catkin_ws/src/traj_gen/qt_ui/qnode.h:11:0,
                 from /home/michael/catkin_ws/src/traj_gen/qt_ui/mainwindow.h:5,
                 from /home/michael/catkin_ws/src/traj_gen/qt_ui/main.cpp:1:
/home/michael/catkin_ws/src/traj_gen/include/traj_gen/PolyTrajGen.h:23:23: fatal error: qpOASES.hpp: No such file or directory
compilation terminated.
traj_gen/CMakeFiles/traj_gen_client.dir/build.make:72: recipe for target 'traj_gen/CMakeFiles/traj_gen_client.dir/qt_ui/main.cpp.o' failed
make[2]: *** [traj_gen/CMakeFiles/traj_gen_client.dir/qt_ui/main.cpp.o] Error 1
In file included from /home/michael/catkin_ws/src/traj_gen/src/PolyTrajGen.cpp:1:0:
/home/michael/catkin_ws/src/traj_gen/include/traj_gen/PolyTrajGen.h:23:23: fatal error: qpOASES.hpp: No such file or directory
compilation terminated.
traj_gen/CMakeFiles/traj_gen_client.dir/build.make:96: recipe for target 'traj_gen/CMakeFiles/traj_gen_client.dir/src/PolyTrajGen.cpp.o' failed
make[2]: *** [traj_gen/CMakeFiles/traj_gen_client.dir/src/PolyTrajGen.cpp.o] Error 1
CMakeFiles/Makefile2:6494: recipe for target 'traj_gen/CMakeFiles/traj_gen_client.dir/all' failed
make[1]: *** [traj_gen/CMakeFiles/traj_gen_client.dir/all] Error 2

Environment:
Ubuntu 16.04 and ROS Kinetic

**Comment by icsl-Jeon** [comment]
Thank you for reporting Issue! 

Did you install the libaray by ```sudo make install``` after make qpOASES?

**Comment by michaelchi08** [comment]
Thanks, the issue was that i was not installing from source. It works and compile fine now. Great work!

**Comment by abdlhersln** [comment]
> Thanks, the issue was that i was not installing from source. It works and compile fine now. Great work!

Hi Mr michaelchi08,
I have same error. How did you solve this problem? I could not get your explanation

**Comment by icsl-Jeon** [comment]
Hello abdlhersln! Did you `sudo make install` after `make` for `qpOASES` ?

**Comment by abdlhersln** [comment]
> Hello abdlhersln! Did you `sudo make install` after `make` for `qpOASES` ?

Hello icsl-Jeon, thanks for your reply. To be honest, I dont know what is 'sudo make install'. Do I need to install from Matlab command window or windows cmd? Could you help me about that? 

Thanks, 
Best regards,

**Comment by icsl-Jeon** [comment]
Which OS do you use? I will assume you have Ubuntu installed.
Please follow [the commands](https://github.com/icsl-Jeon/px4_code2#option-b-manual-step-by-step-installation) in my another repo. Hope it helps.
