### ISSUE TITLE
Min snap vel/acc continuity conditions

### ISSUE THREAD

**Issue by Zhefan-Xu** [icsl-Jeon/traj_gen#10]
https://github.com/icsl-Jeon/traj_gen/blob/9341a5ca2f5dc8f1720d547359d61e74431b12d5/src/PolyTrajGen.cpp#L1096

Hi, I am trying to understand your implementations.
Can you explain a bit about why need to multiply the ```dt2``` term at the end? 
Based on my understanding, you have normalized time interval for each segment to [0, 1], so I don't quite understand why ```dt```appears.

**Comment by icsl-Jeon** [comment]
Sorry for late response. As the line is dealing with first order derivateive conditions, dt should be multiplied.
