### ISSUE TITLE
Does this project suitable for differential wheeled robot?

### ISSUE THREAD

**Issue by stoneman404** [icsl-Jeon/traj_gen#2]
Thanks for this great work! But I didn't know if it is suitable for a differential wheeled robot?

**Comment by icsl-Jeon** [comment]
In case of differential wheeled robot, by the virtue of [differential flatness](https://www.researchgate.net/publication/224118471_Differential_Flatness-based_Kinematic_and_Dynamic_Control_of_a_Differentially_Driven_Wheeled_Mobile_Robot/link/581b6ac608ae40da2ca904b4/download), the robot can track (x,y) trajectory within their actuation limits, where the input terms can be represented with nonlinear combination of high order terms. Thus, In our formulation, imposing nonlinear terms are not possible. However, practically, bounding acceleration (xddot) terms will resolve excessive inputs, which can be handled with 2nd order loosePin. In short, almost yes for (x,y) only setting ```dim = 2```.

**Comment by icsl-Jeon** [comment]
If you have another question in using my library, feel free to contact 

junbs95@gmail.com :)

**Comment by stoneman404** [comment]
It is really a nice work! Thanks for you quick reply, it helps me a lot!
