### ISSUE TITLE
Math question

### ISSUE THREAD

**Issue by tomcattiger1230** [icsl-Jeon/traj_gen#5]
Hello,

I have a question about an equation in your code. 

For example, `sparseBlockCopy<T>(&(abEq.ASet[dd]),tVec(tau,d).transpose()/pow(dt,d),blk,idxStart);`

So according to the definition in papers, there is no `/pow(dt, d)` in the equation. Maybe I have missed something? Can you give me an advice? Thanks.

**Comment by icsl-Jeon** [comment]
That was added due to I have normalized the time parameter. Note that I wrote 'tau' not 't'

**Comment by tomcattiger1230** [comment]
thanks. Got it.
