### ISSUE TITLE
Global max and min speed

### ISSUE THREAD

**Issue by olivierp99** [icsl-Jeon/traj_gen#6]
Hello,

Would it be possible to use global maximum velocity acceleration or jerk instead of passing these loosePin to every waypoint?

Thanks

**Comment by icsl-Jeon** [comment]
Thank you for having an interest in my package.

Unfortunately, enforcing the global condition in the formulation using polynomial is extremely difficult (in general).

The only viable solution, as of now, is to use OptimTrajGen and impose the loose pin in many time sequences as you mentioned. 

Regards
