### ISSUE TITLE
Question about the Q construction

### ISSUE THREAD

**Issue by taec1227** [icsl-Jeon/traj_gen#7]
Hi, I am looking at the cpp implementation, have one question for the objective function for polyTrajGen when compute Q for each segment.
In your code, it is constructed like:
`sparseBlockCopy<T>(&Qd, MatrixRow<T>(IntDerSquard(d) / pow(dt, 2 * d - 1)), m * (N + 1), m * (N + 1));`

How does the ' / pow(dt, 2 * d - 1)' come?  Isn't the fomula 'i*(i-1)*...*(i-d+1)*j*(j-1)*...*(j-d+1)/(i+j-2d+1)*pow(dt, i+j-2d+1)' ?

**Comment by icsl-Jeon** [comment]
https://drive.google.com/file/d/1-HLoRatebe5iK3IfsMdTdux6VXptW9rq/view?usp=sharing

Hope this can help you. Refer page 3.

This is my derivation when building this code.

**Comment by Zhefan-Xu** [comment]
@icsl-Jeon Hi, would you mind share your derivation again? the link expires. THanks!

**Comment by tejalbarnwal** [comment]
> @icsl-Jeon Hi, would you mind share your derivation again? the link expires. THanks!

Yeah, it would be beneficial! Please share the link again for the derivation
