### ISSUE TITLE
Script question

### ISSUE THREAD

**Issue by Iko-Git** [icsl-Jeon/traj_gen#9]
Hello!
Kindly, I want to as if I can, with your software (Python or Matlab version), impose inequality constraints on the first and second derivatives of the piecewise polynomial trajectory. 
What I am aiming to do is to generate a minimum snap piecewise polynomial trajectory (based on a number of 3D waypoints), in which the zeroth (the minimum snap piecewise polynomial), the first (speed), and the second (acceleration)  derivatives won't exceed a certain value.
Any example/guidance would be highly appreciated.

**Comment by tomcattiger1230** [comment]
@Iko-Git  
Hello, I think in my example (the Python implemented) you will see the example you want.
